2024-12-13 10:09:15,986 - INFO - 程序启动
2024-12-13 10:09:21,630 - INFO - 正在启动浏览器，user_id: kr47af7
2024-12-13 10:09:21,630 - INFO - 开始处理商店: Handle Financial, Inc. (环境ID: kr47af7)
2024-12-13 10:09:24,805 - INFO - 浏览器启动成功，信息: {
  "selenium_address": "http://127.0.0.1:53580",
  "debug_port": "53580",
  "user_id": "kr47af7",
  "webdriver": "C:\\Users\\Administrator\\AppData\\Roaming\\adspower_global\\cwd_global\\chrome_130\\chromedriver.exe",
  "puppeteer_ws": "ws://127.0.0.1:53580/devtools/browser/535b097b-ecde-4dbe-bad5-e71909ddd73d"
}
2024-12-13 10:09:24,811 - ERROR - 连接到浏览器失败: object of type 'int' has no len()
2024-12-13 10:09:24,813 - ERROR - selenium_address: http://127.0.0.1:53580
2024-12-13 10:09:24,813 - ERROR - webdriver_path: C:\Users\Administrator\AppData\Roaming\adspower_global\cwd_global\chrome_130\chromedriver.exe
2024-12-13 10:09:24,814 - ERROR - 详细错误信息:
Traceback (most recent call last):
  File "e:\soft\121301\shopify_register\core\browser\adspower.py", line 185, in start_browser_by_id
    self.driver = webdriver.Remote(
                  ~~~~~~~~~~~~~~~~^
        command_executor=selenium_address,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        options=chrome_options
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 241, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 168, in check_response
    if len(value) == 1:
       ~~~^^^^^^^
TypeError: object of type 'int' has no len()
2024-12-13 10:09:24,819 - INFO - 浏览器 kr47af7 已经关闭
2024-12-13 10:09:24,821 - INFO - 任务完成
